### ISSUE TITLE
README contains too much information

### ISSUE THREAD

**Issue by ghost** [greenhost/certbot-haproxy#10]
The README currently walks the use through a complete setup of a server with HAProxy, including configuration of the proxy. This is not relevant for anyone who already has a working proxy and is just looking for instructions to add SSL to their domains.

It's is difficult to identify the pieces of information in the README that are relevant only to setting up `certbot-haproxy` and I think it would be better all the additional information to be removed from the README and moved into another file.

**Comment by SnijderC** [comment]
@mrtndwrd made some changes, would love to hear what you think, better?
