### ISSUE TITLE
Fails to bind using IPv4

### ISSUE THREAD

**Issue by michaelwoods** [greenhost/certbot-haproxy#13]
When I execute certbot with this plugin the certbot server fails to bind at default port 8000 for IPv4. If I watch netstat while this is running, I see port 8000 bound on a IPv6 interface, but as the error indicates nothing on IPv4.

From the debug log:
`DEBUG:acme.standalone:Failed to bind to :8000 using IPv4`

There's no conflict with another service on port 8000 and I've also tried others (e.g. --certbot-haproxy:haproxy-authenticator-haproxy-http-01-port 7999) with corresponding haproxy config changes.

I realize this may be more of a certbot issue but since this plugin is overriding the port I figured I'd start investigating here.

**Comment by SnijderC** [comment]
> There's no conflict with another service on port 8000 and I've also tried others

And that failed too?

Can you tell me something about your OS etc.?

Did you try binding another process to the port to see if that process is able to bind?

**Comment by michaelwoods** [comment]
Yes, the 7999 test failed as well. I am able to listen as an unprivileged user on port 8000.
```
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      22267/nc
```

The OS is raspbian (Debian jesse based). I followed the README instructions to get this setup and my usual port 80 configuration is working fine with haproxy. It just fails to bind to 8000 on the IPv4 side.

Looking through the debug log I can see that it is trying my domain via IPv6 and failing due to my firewall configuration, so I'll be tackling that configuration issue next hopefully working around this.

**Comment by SnijderC** [comment]
Hi Michael, did you ever manage to fix this?

**Comment by michaelwoods** [comment]
No, my setup changed and I now use Let's Encrypt differently.
