### ISSUE TITLE
Failure in step "install certbot-haproxy": failed with error code -9

### ISSUE THREAD

**Issue by cmonty14** [greenhost/certbot-haproxy#17]
Hi,
I'm deploying this app on a server running haproxy on Alpine Linux.
In step "install certbot-haproxy" I get this error:
`vm102-haproxy:/home/certbot-haproxy# python3 -m pip install ./
Processing /home/certbot-haproxy
    Complete output from command python setup.py egg_info:
    ----------------------------------------
Command "python setup.py egg_info" failed with error code -9 in /tmp/pip-oev33ivt-build/
`

Where can I find more Information for troubleshooting this issue?

THX

**Comment by SnijderC** [comment]
Hi, is this issue still relevant? Sorry we didn't notice it before!
