### ISSUE TITLE
Planned changes will break HAProxyAuthenticator

### ISSUE THREAD

**Issue by bmw** [greenhost/certbot-haproxy#24]
Hi! I work at the EFF on Certbot.

In the past, Certbot hasn't been very clear about what parts of its API are public and what parts are private. In preparation of releasing Certbot 1.0, we wanted to be more explicit and offer something stable here so I wrote up https://docs.google.com/document/d/1ozJvEDq2qTtKMeicCUyxH6BZ80_7XZSQDMHMo8uA1WA/edit?usp=sharing which plans to remove Certbot's standalone plugin from our public API which `HAProxyAuthenticator` currently inherits from. All other uses of Certbot's code in your plugin should be unaffected.

We are planning on making this change in our release on December 3rd. I'm sorry for any trouble this causes but I wanted to warn you about the upcoming change.

**Comment by remedycoin** [comment]
This is now officially broken.  Does anybody have a fix now?  I'm seeing the HAProxyAuthenticator problem.  It seems that June 1st was the 1st day they won't accept acme v1.0 queries.

**Comment by frozen-sky** [comment]
Hi,
I've just pushed an update. It works now with more modern versions of certbot. Please read the README.rst, we dropped the installer support and authentication is moved to scripts now, as with the (new, but not so new anymore) handlers this is easier and cleaner.

The project is more a wrapper arround haproxy and certbot command now then a full plugin.
