### ISSUE TITLE
Define certificate directory

### ISSUE THREAD

**Issue by camlafit** [greenhost/certbot-haproxy#5]
With jessie at least should be better to store fullkey in **/etc/letsencrypt/** (as act default certbot package) but files are stored /opt/certbot/haproxy_fullchains/

Is it possible to config this path ?

**Comment by frozen-sky** [comment]
I'm not sure if I agree. Certbot decides to use a separate file file the chain, the key and the certificate. They do not provide a file which has both key, cert and chain. However, if you use haproxy, this is a requirement.

We think it is not wise to interfere with the certbot file/directory structure.

**Comment by camlafit** [comment]
Hi

Yes should be a new directory but following their standard.
Actually we have /etc/letsencrypt/ with individuals certificates and
/opt/certbot/haproxy_fullchains/

Looks better to have standard certbot directory and
/etc/letsencrypt/haproxy_fullchains

**Comment by SnijderC** [comment]
Hi @camlafit, did you try the `--haproxy-crt-dir` argument to the installer? Is this the functionality you are looking for?

**Comment by camlafit** [comment]
Hi

I not sure how about to use. I've tried a certbot run --authentificator --installer --certbot-directory-haproxy and get a unrecognized arguments

**Comment by mrtndwrd** [comment]
There are several reasons why that command fails. We use it like this: 

`certbot run --authenticator certbot-haproxy:haproxy-authenticator --installer certbot-haproxy:haproxy-installer --certbot-haproxy:haproxy-installer-haproxy-restart "<haproxy restart command>"  --certbot-haproxy:haproxy-installer-haproxy-crt-dir <certificate directory> --certbot-haproxy:haproxy-installer-haproxy-config <configuration file path> --domain <domain> --config-dir <certbot configuration>`

Especially note the following things: 

* we need to prefix all certbot-haproxy arguments with `certbot-haproxy:`
* you need to specify an authenticator and an installer
* the authenticator argument is not written as 'authentificator'

Let me know if this helps!

**Comment by camlafit** [comment]
Hi

Thanks a lot :) With these directives look ok.
