### ISSUE TITLE
Mirror looks shutdown

### ISSUE THREAD

**Issue by camlafit** [greenhost/certbot-haproxy#9]
Hi

https://code.greenhost.net/open/certbot-haproxy looks more updated. Mirror is dead or now it's better to move on greenhost server ?

**Comment by camlafit** [comment]
was my bad

**Comment by mrtndwrd** [comment]
There's been some unstable development activity on the Greenhost mirror. When changes there are merged to master, we will also push them to this repository. So in order to not use our unstable development code, I would recommend tracking the github master branch.
